---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.16.0
    container_name: code-server
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PROXY_DOMAIN=code.int.landaalict.nl
      - DEFAULT_WORKSPACE=/projecten
      - PASSWORD=$pass
    volumes:
      - ./config:/config
      - ./projecten:/projecten
    ports:
      - 8989:8443
    restart: unless-stopped

networks:
  proxy:
    external: true