---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - ./backups:/backups
      - /DATA/Data:/Data # Optional Personal config
      - /DATA/Docker:/Docker # Optional Personal config
    ports:
      - 8200:8200
    restart: unless-stopped