version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8089:80
    volumes:
      - ./vw-data:/data
    environment:
      - DOMAIN=https://vault.landaalict.nl
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=$Adminpass
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=5
      - SIGNUPS_DOMAINS_WHITELIST=$domain
      - SMTP_HOST=mail.smtp2go.com
      - SMTP_FROM=info@landaalict.nl
      - SMTP_FROM_NAME=landaalict
      - SMTP_SECURITY=starttls
      - SMTP_PORT=465
      - SMTP_USERNAME=$mailuser
      - SMTP_PASSWORD=$mailpass
networks:
  proxy:
    external: true
