version: '3'
services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    networks:
      - proxy
    ports:
      - '8077:8080'
    environment:
      PICSUR_HOST: '0.0.0.0'
      #PICSUR_PORT: 8080

      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: $dbuser
      PICSUR_DB_PASSWORD: $dbpass
      PICSUR_DB_DATABASE: picsur

      ## The default username is admin, this is not modifyable
      PICSUR_ADMIN_PASSWORD: $adminpass
      
      ## Maximum accepted size for uploads in bytes
      PICSUR_MAX_FILE_SIZE: 128000000
      ## No need to touch this, unless you use a custom frontend
      # PICSUR_STATIC_FRONTEND_ROOT: "/picsur/frontend/dist"

      ## Warning: Verbose mode might log sensitive data
      # PICSUR_VERBOSE: "true"
    restart: unless-stopped
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    networks:
      - proxy
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: $dbpass
      POSTGRES_USER: $dbuser
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  proxy:
    external: true