version: '3.3'
services:
  trilium:
    image: zadam/trilium:latest
    container_name: trilium
    networks:
      - proxy
    ports:
      - 8086:8080
    volumes:
      - ./trilium-data:/home/node/trilium-data
    restart: unless-stopped
networks:
  proxy:
    external: true
