version: '3'

services:
  portainer:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - EULA=TRUE
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
