---
version: "2.1"
services:
  unifi-db:
      image: docker.io/mongo:4.4
      container_name: unifi-db
      networks:
        - proxy
      volumes:
        - ./data:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      restart: unless-stopped
networks:
  proxy:
    external: true
